CREATE DATABASE CSCI467GROUP1A;

CREATE TABLE Login(
    username VARCHAR(50) PRIMARY KEY,
    password VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE WeightBrackets(
    weight FLOAT(4,2) PRIMARY KEY,
    price FLOAT(8,2) NOT NULL
);